/* Generated By:JavaCC: Do not edit this line. ASCII_UCodeESC_CharStream.java Version 0.7pre6 */
package oscript.parser;

import java.util.Deque;
import java.util.Stack;

/**
 * An implementation of interface CharStream, where the stream is assumed to
 * contain only ASCII characters (with java-like unicode escape processing).
 */
public final class ASCII_UCodeESC_CharStream {
    public static Deque<String> _lines;
    private static String _readLine() {
        if (_lines != null) {
            // custom reader
            if (_lines.isEmpty()) {
                _lines = null;
                return null;
            }
            return _lines.removeFirst();
        }
        return null;
    }

    private static final int MASK = 0xFFFF;
    public static final boolean staticFlag = true;

    static final int hexval(char c) {
        switch (c) {
        case '0':
            return 0;
        case '1':
            return 1;
        case '2':
            return 2;
        case '3':
            return 3;
        case '4':
            return 4;
        case '5':
            return 5;
        case '6':
            return 6;
        case '7':
            return 7;
        case '8':
            return 8;
        case '9':
            return 9;

        case 'a':
        case 'A':
            return 10;
        case 'b':
        case 'B':
            return 11;
        case 'c':
        case 'C':
            return 12;
        case 'd':
        case 'D':
            return 13;
        case 'e':
        case 'E':
            return 14;
        case 'f':
        case 'F':
            return 15;
        }

        throw new IllegalArgumentException("Invalid hex digit: " + c);
    }

    static public int bufpos = -1;
    static int bufsize;
    static int available;
    static int tokenBegin;
    static private int bufline[];
    static private int bufcolumn[];
    static private int bufoff[];
    static private int off = 0;
    static private int column = 0;
    static private int line = 1;

    static private boolean prevCharIsCR = false;
    static private boolean prevCharIsLF = false;

    static private char[] nextCharBuf;
    static private char[] buffer;
    static private int maxNextCharInd = 0;
    static private int nextCharInd = -1;
    static private int inBuf = 0;

    static final String CDATA_LEFT = "<![CDATA[";
    static final String CDATA_RIGHT = "]]>";
    static Stack<String> cdataStack = new Stack<String>();

    public static void reset() {
    	 // source-related (do NOT touch _lines; caller sets it)
        nextCharBuf = null;
        maxNextCharInd = 0;
        nextCharInd = -1;     // important: so ReadByte() triggers FillBuff() on first use

        // buffer / token indices
        bufpos = -1;
        tokenBegin = 0;
        bufsize = 0;          // let AdjustBuffSize() -> ExpandBuff(false) allocate on demand
        available = 0;
        inBuf = 0;

        // line/column/offset tracking
        line = 1;
        column = 0;
        off = 0;
        prevCharIsCR = false;
        prevCharIsLF = false;

        // clear CDATA processing state
        if (cdataStack != null)
            cdataStack.clear();
        // allow lazy re-allocation of buffers on first AdjustBuffSize()/ExpandBuff()
        buffer = null;
        bufline = null;
        bufcolumn = null;
        bufoff = null;
    }
    
    static private final void ExpandBuff(boolean wrapAround) {
        int newSize = (bufsize == 0) ? 8192 : bufsize * 2;  // double or start at 2048
        char[] newbuffer = new char[newSize];
        int[] newbufline = new int[newSize];
        int[] newbufcolumn = new int[newSize];
        int[] newbufoff = new int[newSize];

        try {
            if (wrapAround) {
                int firstPart = bufsize - tokenBegin;
                // copy from tokenBegin -> end to beginning
                System.arraycopy(buffer, tokenBegin, newbuffer, 0, firstPart);
                // then copy from start -> bufpos
                System.arraycopy(buffer, 0, newbuffer, firstPart, bufpos);

                System.arraycopy(bufline, tokenBegin, newbufline, 0, firstPart);
                System.arraycopy(bufline, 0, newbufline, firstPart, bufpos);

                System.arraycopy(bufcolumn, tokenBegin, newbufcolumn, 0, firstPart);
                System.arraycopy(bufcolumn, 0, newbufcolumn, firstPart, bufpos);

                System.arraycopy(bufoff, tokenBegin, newbufoff, 0, firstPart);
                System.arraycopy(bufoff, 0, newbufoff, firstPart, bufpos);

                bufpos += firstPart;
            } else {
                int lengthToCopy = bufsize - tokenBegin;
                if (lengthToCopy > 0) {
                    System.arraycopy(buffer, tokenBegin, newbuffer, 0, lengthToCopy);
                    System.arraycopy(bufline, tokenBegin, newbufline, 0, lengthToCopy);
                    System.arraycopy(bufcolumn, tokenBegin, newbufcolumn, 0, lengthToCopy);
                    System.arraycopy(bufoff, tokenBegin, newbufoff, 0, lengthToCopy);
                }
                bufpos -= tokenBegin;
            }
        } catch (Throwable t) {
            throw new Error("Buffer expansion failed: " + t.getMessage(), t);
        }
        buffer = newbuffer;
        bufline = newbufline;
        bufcolumn = newbufcolumn;
        bufoff = newbufoff;
        available = bufsize = newSize;
        tokenBegin = 0;
    }


    static void parseVSCLine(StringBuffer buf, String line, Stack<String> cdataStack) {
        if (line.startsWith(CDATA_LEFT)) {
            if (cdataStack.isEmpty()) {
                line = line.substring(CDATA_LEFT.length(), line.length());
                buf.append("/* ");
                buf.append(CDATA_LEFT);
                buf.append(" */");

            }
            cdataStack.push(CDATA_LEFT);
        }

        if (line.startsWith(CDATA_RIGHT)) {
            if (cdataStack.isEmpty()) {
                throw new IllegalStateException("Tag " + CDATA_RIGHT + " without preceeding " + CDATA_LEFT);
            }
            cdataStack.pop();
            if (cdataStack.isEmpty()) {
                buf.append("\"\"/* ");
                buf.append(CDATA_RIGHT);
                buf.append(" */");
                buf.append(line.substring(CDATA_RIGHT.length(), line.length()));
                return;
            }
        }

        if (cdataStack.isEmpty()) {
            buf.append(line);
        } else {
            buf.append("\"");
            line = line.replace("\\", "\\\\");
            buf.append(line.replace("\"", "\\\""));
            buf.append("\\n\" + ");
        }
    }

    static private final boolean FillBuff() {
        if (_lines == null) {
            maxNextCharInd = 0;
            nextCharInd = 0;
            return false;
        }
        String line;
        StringBuffer buf = new StringBuffer();
        while ((line = _readLine()) != null) {
            // System.out.println(count++ + ": " + line);
            parseVSCLine(buf, line, cdataStack);
            buf.append("\n");
            if (buf.length() >= 16384)
                break;
        }
        if (buf.length() == 0) {
            maxNextCharInd = 0;
            nextCharInd = 0;
            return false;
        }
        if (nextCharBuf == null || buf.length() > nextCharBuf.length) {
            nextCharBuf = new char[buf.length()];
        }
        buf.getChars(0, buf.length(), nextCharBuf, 0);
        maxNextCharInd = buf.length();
        nextCharInd = 0;
        return true;
    }

    static private final int ReadByte() {
        if (++nextCharInd >= maxNextCharInd) {
            if (!FillBuff()) {
                return -1;
            }
        }

        return nextCharBuf[nextCharInd];
    }

    static public final int BeginToken() {
        if (inBuf > 0) {
            --inBuf;
            return buffer[tokenBegin = (bufpos == bufsize - 1) ? (bufpos = 0) : ++bufpos];
        }

        tokenBegin = 0;
        bufpos = -1;

        return readChar();
    }

    static private final void AdjustBuffSize() {
        if (available == bufsize) {
            if (tokenBegin > 2048) {
                bufpos = 0;
                available = tokenBegin;
            } else
                ExpandBuff(false);
        } else if (available > tokenBegin)
            available = bufsize;
        else if ((tokenBegin - available) < 2048)
            ExpandBuff(true);
        else
            available = tokenBegin;
    }

    static private final void UpdateLineColumn(char c) {
        column++;

        if (prevCharIsLF) {
            prevCharIsLF = false;
            line += (column = 1);
        } else if (prevCharIsCR) {
            prevCharIsCR = false;
            if (c == '\n') {
                prevCharIsLF = true;
            } else
                line += (column = 1);
        }

        switch (c) {
        case '\r':
            prevCharIsCR = true;
            break;
        case '\n':
            prevCharIsLF = true;
            break;
        case '\t':
            column--;
            column += (8 - (column & 07));
            break;
        default:
            break;
        }

        bufline[bufpos] = line;
        bufcolumn[bufpos] = column;
        bufoff[bufpos] = off++;
    }

    static public final int readChar() {
        if (inBuf > 0) {
            --inBuf;
            return buffer[(bufpos == bufsize - 1) ? (bufpos = 0) : ++bufpos];
        }

        char c;

        if (++bufpos == available)
            AdjustBuffSize();

        int byteRead = ReadByte();
        if (byteRead == -1) {
            if (bufpos != 0) {
                --bufpos;
            } else {
                bufline[bufpos] = line;
                bufcolumn[bufpos] = column;
                bufoff[bufpos] = off;
            }
            return -1;
        }

        if (((buffer[bufpos] = c = (char) ((char) MASK & byteRead)) == '\\')) {
            UpdateLineColumn(c);

            int backSlashCnt = 1;

            for (;;) // Read all the backslashes
            {
                if (++bufpos == available)
                    AdjustBuffSize();

                int nextByte = ReadByte();
                if (nextByte == -1) {
                    if (backSlashCnt > 1)
                        backup(backSlashCnt);

                    return '\\';
                }
                if ((buffer[bufpos] = c = (char) ((char) MASK & nextByte)) != '\\') {
                    UpdateLineColumn(c);
                    // found a non-backslash char.
                    if ((c == 'u') && ((backSlashCnt & 1) == 1)) {
                        if (--bufpos < 0)
                            bufpos = bufsize - 1;

                        break;
                    }

                    backup(backSlashCnt);
                    return '\\';
                }

                UpdateLineColumn(c);
                backSlashCnt++;
            }

            // Here, we have seen an odd number of backslash's followed by a 'u'
            // do we need to update offset here?
            int nextByte = ReadByte();
            if (nextByte == -1)
                throw new Error("Invalid escape character at line " + line + " column " + column + ".");
            c = (char) ((char) MASK & nextByte);
            while (c == 'u') {
                ++column;
                nextByte = ReadByte();
                if (nextByte == -1)
                    throw new Error("Invalid escape character at line " + line + " column " + column + ".");
                c = (char) ((char) MASK & nextByte);
            }

            int c1 = hexval(c);
            int c2 = ReadByte();
            int c3 = ReadByte();
            int c4 = ReadByte();
            if (c2 == -1 || c3 == -1 || c4 == -1)
                throw new Error("Invalid escape character at line " + line + " column " + column + ".");

            buffer[bufpos] = c = (char) (c1 << 12 | hexval((char) ((char) MASK & c2)) << 8
                    | hexval((char) ((char) MASK & c3)) << 4 | hexval((char) ((char) MASK & c4)));

            column += 4;

            if (backSlashCnt == 1)
                return c;
            else {
                backup(backSlashCnt - 1);
                return '\\';
            }
        } else {
            UpdateLineColumn(c);
            return c;
        }
    }

    static public final int getEndColumn() {
        return bufcolumn[bufpos];
    }

    static public final int getEndLine() {
        return bufline[bufpos];
    }

    static public final int getBeginColumn() {
        return bufcolumn[tokenBegin];
    }

    static public final int getBeginLine() {
        return bufline[tokenBegin];
    }

    static public final int getBeginOffset() {
        return bufoff[tokenBegin];
    }

    static public final int getEndOffset() {
        return bufoff[bufpos];
    }

    static public final void backup(int amount) {

        inBuf += amount;
        if ((bufpos -= amount) < 0)
            bufpos += bufsize;
    }


    static public final String GetImage() {
        if (bufpos >= tokenBegin)
            return new String(buffer, tokenBegin, bufpos - tokenBegin + 1);
        else
            return new String(buffer, tokenBegin, bufsize - tokenBegin) + new String(buffer, 0, bufpos + 1);
    }

    static public final char[] GetSuffix(int len) {
        char[] ret = new char[len];

        if ((bufpos + 1) >= len)
            System.arraycopy(buffer, bufpos - len + 1, ret, 0, len);
        else {
            System.arraycopy(buffer, bufsize - (len - bufpos - 1), ret, 0, len - bufpos - 1);
            System.arraycopy(buffer, 0, ret, len - bufpos - 1, bufpos + 1);
        }

        return ret;
    }

    static public void Done() {
        nextCharBuf = null;
        buffer = null;
        bufline = null;
        bufcolumn = null;
        bufoff = null;
    }

    /**
     * Method to adjust line and column numbers for the start of a token.<BR>
     */
    static public void adjustBeginLineColumn(int newLine, int newCol) {
        int start = tokenBegin;
        int len;

        if (bufpos >= tokenBegin) {
            len = bufpos - tokenBegin + inBuf + 1;
        } else {
            len = bufsize - tokenBegin + bufpos + 1 + inBuf;
        }

        int i = 0, j = 0, k = 0;
        int nextColDiff = 0, columnDiff = 0;

        while (i < len && bufline[j = start % bufsize] == bufline[k = ++start % bufsize]) {
            bufline[j] = newLine;
            nextColDiff = columnDiff + bufcolumn[k] - bufcolumn[j];
            bufcolumn[j] = newCol + columnDiff;
            columnDiff = nextColDiff;
            i++;
        }

        if (i < len) {
            bufline[j] = newLine++;
            bufcolumn[j] = newCol + columnDiff;

            while (i++ < len) {
                if (bufline[j = start % bufsize] != bufline[++start % bufsize])
                    bufline[j] = newLine++;
                else
                    bufline[j] = newLine;
            }
        }

        line = bufline[j];
        column = bufcolumn[j];
        off = bufoff[j];
    }
}
